// AstraForge GitHub Integration Content Script

// Inject AstraForge UI elements into GitHub
function injectAstraForgeUI() {
  // Add AstraForge button to repository header
  const repoHeader = document.querySelector('.gh-header-actions');
  if (repoHeader && !document.querySelector('.astraforge-btn')) {
    const astraBtn = document.createElement('button');
    astraBtn.className = 'astraforge-btn btn btn-sm';
    astraBtn.innerHTML = '🌌 AstraForge';
    astraBtn.style.backgroundColor = '#8b5cf6';
    astraBtn.style.color = 'white';
    astraBtn.style.border = 'none';
    astraBtn.style.borderRadius = '6px';
    astraBtn.style.padding = '5px 12px';
    astraBtn.style.fontSize = '12px';
    astraBtn.style.fontWeight = '500';
    astraBtn.style.cursor = 'pointer';
    astraBtn.style.marginLeft = '8px';

    astraBtn.addEventListener('click', () => {
      // Open extension popup
      chrome.runtime.sendMessage({
        type: 'OPEN_POPUP'
      });
    });

    repoHeader.appendChild(astraBtn);
  }

  // Add AI suggestions to PR reviews
  const prTimeline = document.querySelector('.js-discussion');
  if (prTimeline && !document.querySelector('.astraforge-pr-suggestions')) {
    const suggestionsBox = document.createElement('div');
    suggestionsBox.className = 'astraforge-pr-suggestions';
    suggestionsBox.style.cssText = `
      background: #f6f8fa;
      border: 1px solid #d1d9e0;
      border-radius: 6px;
      padding: 16px;
      margin: 16px 0;
      font-size: 14px;
    `;

    suggestionsBox.innerHTML = `
      <div style="display: flex; align-items: center; margin-bottom: 8px;">
        <span style="font-weight: 600; color: #24292f;">🤖 AstraForge AI Review</span>
        <span style="background: #ddf4ff; color: #0969da; padding: 2px 8px; border-radius: 12px; font-size: 12px; margin-left: 8px;">Beta</span>
      </div>
      <div style="color: #656d76; line-height: 1.5;">
        Analyzing this pull request... AI suggestions will appear here shortly.
      </div>
    `;

    // Insert after PR title
    const prTitle = document.querySelector('.js-issue-title');
    if (prTitle && prTitle.parentNode) {
      prTitle.parentNode.insertBefore(suggestionsBox, prTitle.nextSibling);
    }

    // Simulate AI analysis
    setTimeout(() => {
      suggestionsBox.innerHTML = `
        <div style="display: flex; align-items: center; margin-bottom: 12px;">
          <span style="font-weight: 600; color: #24292f;">🤖 AstraForge AI Review</span>
          <span style="background: #ddf4ff; color: #0969da; padding: 2px 8px; border-radius: 12px; font-size: 12px; margin-left: 8px;">Complete</span>
        </div>
        <div style="margin-bottom: 12px;">
          <div style="font-weight: 500; color: #24292f; margin-bottom: 4px;">✅ Code Quality: Good</div>
          <div style="color: #656d76; font-size: 13px;">Well-structured code with proper error handling</div>
        </div>
        <div style="margin-bottom: 12px;">
          <div style="font-weight: 500; color: #24292f; margin-bottom: 4px;">⚠️ Suggestions</div>
          <ul style="color: #656d76; font-size: 13px; margin: 0; padding-left: 16px;">
            <li>Add unit tests for the new authentication logic</li>
            <li>Consider adding TypeScript types for better safety</li>
            <li>Update documentation for the new API endpoints</li>
          </ul>
        </div>
        <div style="font-size: 12px; color: #656d76;">
          Generated by AstraForge AI • <a href="#" style="color: #0969da;">View full analysis</a>
        </div>
      `;
    }, 3000);
  }

  // Add code suggestions to files
  const fileHeaders = document.querySelectorAll('.file-header');
  fileHeaders.forEach(header => {
    if (!header.querySelector('.astraforge-file-ai')) {
      const aiBtn = document.createElement('button');
      aiBtn.className = 'astraforge-file-ai';
      aiBtn.innerHTML = '🤖';
      aiBtn.title = 'Get AI suggestions for this file';
      aiBtn.style.cssText = `
        background: none;
        border: none;
        cursor: pointer;
        padding: 4px;
        border-radius: 3px;
        font-size: 14px;
        margin-left: 8px;
      `;

      aiBtn.addEventListener('mouseenter', () => {
        aiBtn.style.backgroundColor = '#f6f8fa';
      });

      aiBtn.addEventListener('mouseleave', () => {
        aiBtn.style.backgroundColor = 'transparent';
      });

      aiBtn.addEventListener('click', () => {
        const fileName = header.querySelector('.Link--primary')?.textContent;
        if (fileName) {
          analyzeFile(fileName, header);
        }
      });

      header.appendChild(aiBtn);
    }
  });
}

// Analyze a specific file with AI
function analyzeFile(fileName, headerElement) {
  // Find the file content
  const fileContainer = headerElement.closest('.file');
  const codeElement = fileContainer?.querySelector('.blob-code');

  if (codeElement) {
    // Show loading state
    const loadingDiv = document.createElement('div');
    loadingDiv.style.cssText = `
      background: #fff3cd;
      border: 1px solid #ffeaa7;
      border-radius: 6px;
      padding: 12px;
      margin: 8px 0;
      font-size: 13px;
      color: #856404;
    `;
    loadingDiv.innerHTML = '🤖 Analyzing file with AstraForge AI...';

    headerElement.parentNode.insertBefore(loadingDiv, headerElement.nextSibling);

    // Simulate AI analysis
    setTimeout(() => {
      loadingDiv.style.backgroundColor = '#d1ecf1';
      loadingDiv.style.borderColor = '#bee5eb';
      loadingDiv.style.color = '#0c5460';
      loadingDiv.innerHTML = `
        <strong>🤖 AstraForge Analysis Complete</strong><br>
        <strong>File:</strong> ${fileName}<br>
        <strong>Issues:</strong> 2 minor suggestions<br>
        <strong>Complexity:</strong> Low<br>
        <strong>Coverage:</strong> 85%<br><br>
        <em>Suggestions:</em><br>
        • Consider adding JSDoc comments<br>
        • Extract magic numbers to constants
      `;
    }, 2000);
  }
}

// Handle messages from background script
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  switch (request.type) {
    case 'CONTEXT_MENU_ANALYZE':
      injectAstraForgeUI();
      break;
  }
});

// Initialize when page loads
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', injectAstraForgeUI);
} else {
  injectAstraForgeUI();
}

// Watch for navigation changes (GitHub uses SPA)
let currentUrl = location.href;
new MutationObserver(() => {
  if (location.href !== currentUrl) {
    currentUrl = location.href;
    setTimeout(injectAstraForgeUI, 1000);
  }
}).observe(document, { subtree: true, childList: true });
